apiVersion: apps/v1
kind: Deployment
metadata:
  name: libraryapp
  namespace: test
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: libraryapp
  template:
    metadata:
      labels:
        app: libraryapp
    spec:
      restartPolicy: Always
      containers:
      - name: libraryapp
        image: docker.io/javiergarciagon/mca-m4-a4-pr2:v1
        resources:
          requests:
            cpu: "200m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8881
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/test
        - name: SERVER_PORT
          value: "8881"
---
apiVersion: v1
kind: Service
metadata:
  name: libraryapp
  namespace: test
  labels:
    app: libraryapp
spec:
  ports:
  - port: 8881
    targetPort: 8881
    protocol: TCP
    name: libraryapp-port
  selector:
    app: libraryapp
  type: ClusterIP
